import { Link } from 'react-router-dom'

export function More() {
  return (
    <>
      <h1>More</h1>
      <Link to="/exercises" className="card row-between" style={{ display: 'flex' }}>
        <span style={{ color: 'var(--text-h)' }}>🏋️ Exercises</span>
        <span className="muted">manage lifts & increments</span>
      </Link>
      <Link to="/settings" className="card row-between" style={{ display: 'flex' }}>
        <span style={{ color: 'var(--text-h)' }}>⚙️ Settings</span>
        <span className="muted">units, e1RM formula</span>
      </Link>
      <p className="muted" style={{ marginTop: 16 }}>
        AI insights are generated by Claude from your logged training data. Anything marked
        “✨ AI-generated” came from the model; all numbers are computed locally.
      </p>
    </>
  )
}
